### ISSUE TITLE
npm test no longer run

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/keycloak-admin-client#13]
Looks like npm test is no longer run in the ci target.

also there seems to be an error in the after_success handler:

`The command "make ci" exited with 0.
after_success
0.37s$ cat ./coverage/lcov.info | coveralls
cat: ./coverage/lcov.info: No such file or directory
[error] "2016-11-04T17:53:20.528Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2016-11-04T17:53:20.531Z"  'input: ' ''
[error] "2016-11-04T17:53:20.531Z"  'error from convertLcovToCoveralls'
/home/travis/.nvm/versions/node/v4.6.1/lib/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Failed to parse string`

**Comment by helio-frota** [comment]
bucharest-gold/entente#133

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/keycloak-admin-client/commit/f174e48d5906280c06a6c7ff60998cc59380484d
