### ISSUE TITLE
What does it mean that the project is "Extremely Experimental"?

### ISSUE THREAD

**Issue by pandapaul** [bucharest-gold/keycloak-admin-client#19]
Howdy.  I'm considering building a user onboarding/management tool around keycloak-admin-client, but I want to get a good sense of what you all mean when you refer to the project as "Extremely Experimental."  I feel like I can safely assume that the project is considered to be still in active development and that some volatility is to be expected.  That's no problem by me, but I'm hoping you can help me set my expectations regarding breaking changes, the future of the package, and whatever else I should be aware of before using it in a production environment.

Thank ya kindly.

**Comment by lholmquist** [comment]
@pandapaul thanks for the interest.    

I think what you've described is accurate. We haven't done a 1.0 release so things could be in flux.  But i think the API is generally were we wanted it to be.

There are of course a lot more features that can be added(There are a lot more REST endpoints).

I'm not sure the last version i tested it on,  but there is a PR that is trying to get us to the most recent version of Keycloak.

If you are using it,  don't hesitate to ask questions.

**Comment by pandapaul** [comment]
Awesome.  I'm beginning to use it today, so if any issues or questions comes up I'll absolutely ask.  Thanks very much!

**Comment by helio-frota** [comment]
>I'm not sure the last version i tested it on, but there is a PR that is trying to get us to the most recent version of Keycloak.

@lholmquist @pandapaul 
landed here: https://github.com/bucharest-gold/keycloak-admin-client/commit/6abafb170b6ed7b9d47895cbb72a6fac05dfa3d8
