### ISSUE TITLE
Assigning client roles to users & updating passwords

### ISSUE THREAD

**Issue by pandapaul** [bucharest-gold/keycloak-admin-client#22]
Is it possible to assign client roles to users via `client.users.update()`?  I'm attempting to do so by setting `user.clientRoles` to something like
```js
  {
    aClient: [
      'anAssignableClientRole'
    ]
  }
```

Now that's just ripped off from some example realm JSON I stumbled on here:  https://github.com/keycloak/keycloak/blob/1aeec2a83c6677cd7dcfccb6ba2c39d10143b920/examples/authz/photoz/photoz-realm.json

I know that the users update method uses the `/admin/realms/{realm}/users/{id}` route documented here:  http://www.keycloak.org/docs-api/3.1/rest-api/index.html#_updateuser  but the documentation there really isn't clear regarding what is possible.

I'm also wondering if the admin client currently provides any way to update a user's password.

**Comment by lholmquist** [comment]
@pandapaul so to answer your first question,  it doesn't look like it.

Here is the keycloak code for the route, https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java#L153 ,  and here is the function that does the update:  https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java#L245

Doesn't look like it updates the client stuff in there.


For the second question, i don't believe there is anything yet on password updates in our client,  but i think the only thing that is available from the REST endpoints is to reset the password.  I don't think that is implemented yet either.  could be a nice contribution :) :)

**Comment by pandapaul** [comment]
Ok cool.  Yeah I'm using different routes to do both of those things, so those would indeed make for some nice contribution :)  Going to close this issue since my questions are answered.  Thanks!
