### ISSUE TITLE
problem with const

### ISSUE THREAD

**Issue by teegwende** [bucharest-gold/keycloak-admin-client#40]
Hi all,
i had an issue to run an application which integrate keycloak-admin-client on iceweasel-firefox ESR 45.9.
when i run it the browser launches but it just shows localhost:3000 and nothing else.
I opened the web console to check and I see "SyntaxError: invalid for/in left-hand side" . when i clicked on the error it showed me that the problem is with a loop where const is used. See attached the picture for more details

Regards

![details_of_error](https://user-images.githubusercontent.com/26285604/27027605-a325f83c-4f51-11e7-9192-4db489993252.png)

**Comment by helio-frota** [comment]
@teegwende thanks for the report !
The project was not published yet, but you can install from the source to test.

**Comment by helio-frota** [comment]
@teegwende hi,
You can use test again now.
https://www.npmjs.com/package/keycloak-admin-client
@lholmquist thanks!
