### ISSUE TITLE
Missing keycloak-admin-client.js

### ISSUE THREAD

**Issue by muhilan** [bucharest-gold/keycloak-admin-client#9]
When I did a
` npm install keycloak-admin-client `, i see that the lib/keycloak-admin-client.js is missing. since index.js looks for lib/keycloak-admin-client.js, I am unable to use this module. I use version  `keycloak-admin-client@0.3.1`. 
```
$ npm -v
3.8.3
```

**Comment by lholmquist** [comment]
@muhilan i am seeing it also,  i think i know the issue,   npm uses my .gitignore for the .npmignore and i'm ignoring keycloak* , so looks like that might have been it,  

I just renamed that file and released a 0.4.0, 

i needed to do a rm -rf node_modules and then a npm install keycloak-admin-client@0.4.0 for it to show up.


I'll close this once you are successful

**Comment by muhilan** [comment]
Works fine now. Thanks a lot.
